### ISSUE TITLE
import.meta.glob + defineAsyncComponent not working build

### ISSUE THREAD

**Issue by alquezajanmaverick** [barrel/barrel-shopify#13]
✅ This works on development as it is fetched on dev server.
❌ Doesn't work on Production. ( Produces chunks per component as desired but ) No 404 files resource but stays blank
```
const components = import.meta.glob('./../components/*.vue')
for ( const path  in components) {
  const result = 'App'+_.upperFirst(_.camelCase(path.split('/').pop().replace(/\.\w+$/, '')))
  const modulesContent = components[path]
  app.component(result,  defineAsyncComponent(modulesContent))
}
```

✅  This 👇 works on both dev and production mode ( Produces  single file with all components with it )
```
const componentFiles = import.meta.glob('./../components/*.vue',{ eager:true });
Object.entries(componentFiles).forEach(([path, m]) => {

  const componentName = 'App'+_.upperFirst(
    _.camelCase(path.split('/').pop().replace(/\.\w+$/, ''))
  );
  app.component(componentName, m.default)
})
```

I don't want to load all components at once since some components are not being used on specific pages.
Is there any configurations I missed? or?

I am using Vue 3.

**Comment by montalvomiguelo** [comment]
@alquezajanmaverick You would want to lazy-load those components via dynamic imports so they're split into separate chunks. https://vitejs.dev/guide/features.html#glob-import

```
const components = import.meta.glob('../components/**.vue')

Object.keys(components).forEach(key => {
  const name = key.match(/^\.\.\/components\/(.*)\.vue$/)[1]
  app.component(name, defineAsyncComponent(() => components[key]()))
})
```

I created this quick example for you.
https://github.com/barrel/barrel-shopify/tree/vue-example/themes/vite-shopify-example


Preview with.
https://montalvomiguelo.myshopify.com/?preview_theme_id=124717465648

**Comment by alquezajanmaverick** [comment]
Still produces the same result 😢
the thing is: I have my components rendered inside content_for_layout so my theme.liquid body will be 
```
<div id="app">
 {{ content_for_layout }}
</div>
```
and the sample index section would have components like `<hello-world/>`

`root -> content_for_layout -> index.json -> index-banner.liquid -> <hello-world/>`

I am importing `vue/dist/vue.esm-bundler` instead of `vue`.

**Comment by montalvomiguelo** [comment]
@alquezajanmaverick I am not super familiar with vue 😅

I had to take some ideas from [uicrooks/shopify-foundation-theme](https://github.com/uicrooks/shopify-foundation-theme) to update [the quick example](https://github.com/barrel/barrel-shopify/tree/vue-example/themes/vite-shopify-example) I created for you. I don't see any error related to the functionality of our plugin.

https://montalvomiguelo.myshopify.com/?preview_theme_id=124717465648

Check this note re [in-browser template compilation](https://vuejs.org/guide/scaling-up/tooling.html#note-on-in-browser-template-compilation). It looks like on prod mode, vue resolves to vue.runtime.esm-bundler.js, which requires templates to be pre-compiled during a build step.

**Comment by alquezajanmaverick** [comment]
@montalvomiguelo the issue on vue is resolved but is not automatic, I had to edit the `vite-tag.liquid` every time after production. The issue was on the versioning per file. Liquid appends ?v=[randomhash] to every file that is being called. 

I have been using the uicrooks/shopify-foundation theme for a year now. It might be a good time to test on vite since the said  framework uses webpack. 

Hopefully I can finish this local branch i have to contribute on this repo 😅

**Comment by alquezajanmaverick** [comment]
@montalvomiguelo the sample you made is registering the components as global component (not by using defineAsyncComponent)😅. There's really no issue on registering components globally other than performance.
There's no code-splitting when using app.component([ComponentName],[component])

**Comment by alquezajanmaverick** [comment]
removing this solves the issue 😅
<img width="453" alt="Screen Shot 2022-10-20 at 4 21 23 PM" src="https://user-images.githubusercontent.com/10112754/196896609-a165786a-2ebb-4900-9767-c2380ae9d231.png">

I think it can only be done by adding feature on the plugin as it is auto-generated
<img width="1002" alt="Screen Shot 2022-10-20 at 4 24 19 PM" src="https://user-images.githubusercontent.com/10112754/196896757-b9a7200d-440d-4a9f-a67b-3ed1a86e5266.png">

**Comment by montalvomiguelo** [comment]
@alquezajanmaverick The ?v=[randomhash] is a version control number automatically generated by using the asset_url filter and ensures we're getting the latest version back for a given asset. Currently we don't have plans to mutate that behavior

**Comment by montalvomiguelo** [comment]
@alquezajanmaverick we have removed the querystring from asset urls in #21 :D

**Comment by plcdnl** [comment]
Hi @montalvomiguelo , sorry to bother you.

I noticed that your example of using Shopify with Vue is no longer available. Are you still working with that setup? If so, I’d really appreciate it if you could share it with me or point me in the right direction. Thanks in advance!

**Comment by janaipakos** [comment]
> Hi [@montalvomiguelo](https://github.com/montalvomiguelo) , sorry to bother you.
> 
> I noticed that your example of using Shopify with Vue is no longer available. Are you still working with that setup? If so, I’d really appreciate it if you could share it with me or point me in the right direction. Thanks in advance!

bump
