### ISSUE TITLE
Shopfiy HotReload not working with plugin

### ISSUE THREAD

**Issue by laugepetersen** [barrel/barrel-shopify#14]
Hello,

Amazing plugin, but here is an issue:

When serving a shopify theme with the CLI:
`shopify theme serve`

Together with Vite + your plugin:
`vite dev`

And running on localhost:
`http://127.0.0.1:9292`

Then the HotReload SSE connection returns 404 - not found.

The changes made through css/scss or js is reloaded. But when changing liquid files such as `sections` it needs to be manually refreshed inorder to kick in. And with some delay.

If i don't run `vite dev`, the shopify HotReload works perfectly fine.

**Comment by montalvomiguelo** [comment]
@laugepetersen which version of these things are you running?

- vite
- vite-plugin-shopify
- shopify-cli
- node
- npm
- pnpm?
- yarn?

**Comment by laugepetersen** [comment]
> @laugepetersen which version of these things are you running?
> 
>     * vite
> 
>     * vite-plugin-shopify
> 
>     * shopify-cli
> 
>     * node
> 
>     * npm
> 
>     * pnpm?
> 
>     * yarn?

vite: 3.1.8
vite-plugin-shopify: 0.0.5
shopify-cli: 2.27.0
node: 16.18.0
npm: 8.19.2

**Comment by montalvomiguelo** [comment]
Thanks @laugepetersen

I am not able to reproduce this issue on my end

<img width="400px" alt="Screen Shot 2022-10-18 at 3 25 25 PM" src="https://user-images.githubusercontent.com/5134470/196556897-33a10729-7b1f-4162-a2e5-1b83964345d4.png">





Lets try [upgrading your shopify-cli version](https://shopify.dev/themes/tools/cli/upgrade-uninstall#upgrade-shopify-cli) to [2.28.0](https://github.com/Shopify/shopify-cli/releases/tag/v2.28.0)

**Comment by laugepetersen** [comment]
Didn't help upgrading to 2.28.0...

![billede](https://user-images.githubusercontent.com/24874516/196717548-8a147212-6720-4328-bc0b-3a84ab6fcdaa.png).

I just list some images if they help in any way:

<img width="277" alt="billede" src="https://user-images.githubusercontent.com/24874516/196717710-71886320-ddec-4c2c-884b-b678f5f08ac6.png">

Vite terminal on change:
![billede](https://user-images.githubusercontent.com/24874516/196717867-e1d3257b-aed1-4bdd-aa5b-68db974a56d9.png)

Shopify terminal on change:
![billede](https://user-images.githubusercontent.com/24874516/196717999-584fbdec-edce-4d92-8bd5-c671c44e9bac.png)

**Comment by montalvomiguelo** [comment]
@laugepetersen not sure why the shopify-cli throws `[Hotreload SSE closed]` on your end. I believe I found [your project](https://github.com/laugepetersen/shopify-liquid-theme)? and [everything is running properly for me](https://imgur.com/a/k93wep8)

**Comment by laugepetersen** [comment]
Thanks a lot for your help.
I have found out that **Firefox** is the only browser not connecting to HotReload. **Chrome** does the job. Didn't think of this before now.
