### ISSUE TITLE
Vite-Tag Path Delimiter Issue on Windows

### ISSUE THREAD

**Issue by ChristianS-Nextint** [barrel/barrel-shopify#35]
I noticed that when running vite-plugin-shopify on Windows, the generated vite-tag.liquid includes the wrong path delimiter.
On windows it generates
`{% assign path = vite-tag | replace: '~/', '../' | replace: '@/', '../' | replace: '@modules/', '..\..\modules/' | replace: '~modules/', '..\..\modules/' %}`
while on macOS it generates
`{% assign path = vite-tag | replace: '~/', '../' | replace: '@/', '../' | replace: '@modules/', '../../modules/' | replace: '~modules/', '../../modules/' %}`
The usages of the windows path delimiter \ breaks the matching here and it seems instead always the unix path delimiter / should be used.

For Example vite-tag gets rendered like this: `{% render 'vite-tag' with '@modules/hero-slider/hero-slider.js' %}`
And the vite-tag replaces '**@modules/**' with '**..\..\modules/**' and then tries to match it below with '**..\..\modules\hero-slider\hero-slider.js**'

I've attached the example vite-tag.liquid here:
[vite-tag.txt](https://github.com/barrel/barrel-shopify/files/10435857/vite-tag.txt)

**Comment by montalvomiguelo** [comment]
Hey @ChristianS-Nextint, Could you share your vite config file and vite plugins (with the versions) so I can try to reproduce this issue? 🙏
