### ISSUE TITLE
Vite tag is ignoring Shopify CDN disk cache logic by using the filter `asset_url | split: '?' | first ` 

### ISSUE THREAD

**Issue by iska31** [barrel/barrel-shopify#36]
Hello, 

I upgraded the plugin to the lastest version and I got some issues cause of the liquid filter used in the vite-tag snippet : 
`asset_url | split: '?' | first ` 

Indeed removing the versioning after the `?` makes our website requesting the same asset name, and thus the Shopify CDN for the current theme (cf asset_url) keep delivering outdated assets.
Ex :
- Create my_script.js 
- Build and push your theme
- Edit my_script.js
- Build and push and override your theme using last version of the plugin.
- --> You will see in your network tab that the url is hitting the CDN returning a disk cache version, thus you don't see your changes on the my_script.js file (the DOM either!).

My solution was to downgrade the plugin to `"vite-plugin-shopify": "^0.0.5",` ; which was a version I used on another project and it works perfectly as the vite-tag snippet do not use the split from `asset_url | split: '?' | first `

Could you guys do something about it ? 
Haven't got the time to PR it

Though, why such a choice for the vite tag snippet?

Regards 
Iska

**Comment by montalvomiguelo** [comment]
Hey @iska31 

* We leverage the `[hash]` of the file names to ensure we always ship the latest version for a given asset
* The `[hash]` will change depending on the content of the asset
* The `?v=` param was removed in #21 to avoid downloading assets twice 

https://user-images.githubusercontent.com/5134470/213600386-0fbb0d7e-e6e7-4719-8d0e-9e562dedee7a.mp4

**Comment by iska31** [comment]
Hey!

Thank you for your message.
I will re test again today. This was not working for me with css assets. My
bad I mentioned js files.
